config/routes.rb
Hubstar::Application.routes.draw do
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  get 'sign_in', :to => 'sessions#new', :as => :sign_in
  delete 'sign_out', :to => 'sessions#destroy', :as => :sign_out

  get 'about', :to => 'dashboard#about', :as => :about

  resources :repositories, :only => [:index, :show], :id => /[\w\-\+\/\.]+/
  resource :star, :only => [:update, :destroy]

  root :to => 'dashboard#index'
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  attr_accessible :name, :description, :watchers, :forks, :language, :user

  validates :name, uniqueness: true, format: /^[^\/]+\/[^\/]+$/

  has_and_belongs_to_many :users, uniq: true, order: :id

  def to_s
    name
  end

  def to_param
    name
  end

  # Override as_json so that we can insert some attributes into the resulting
  # object
  #
  # Inserts the number of users that have starred this Repository in the
  # <tt>stars</tt> attribute, and, if given a <tt>:user</tt> argument, checks
  # if the given user has starred this repository in the <tt>hubstarred</tt>
  # attribute.
  def as_json(*args)
    u = args.first.delete(:user)
    hash = super(*args)
    hash.merge!({hubstarred: has_user?(u), stars: stars})
  end

  # Checks if the given user is present in the record's <tt>users</tt> array.
  def has_user?(user)
    if user.nil?
      false
    else
      self.users.where(id: user.id).count == 1
    end
  end

  # Public: Get an array of users who have starred this repository, giving
  # priority in sorting to the supplied user argument.
  #
  # user - The user to which priority should be given
  #
  # Returns the sorted array of user records.
  def users_with_priority_to(user)
    users = self.users

    # If the user exists in the array and is not currently the first element,
    # move it there
    if users.include?(user) && users[0] != user
      users.insert(0, users.slice!(users.index(user)))
    end

    users
  end

  # Allows mass-assignment to add a single user to the collection
  def user=(value)
    users << value
  end

  def link
    "https://github.com/#{name}"
  end

  def stars
    users.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :github_data, :github_access_token

  serialize :github_data

  delegate :login, :avatar_url, :html_url, :name, to: :github_data

  has_and_belongs_to_many :repositories, uniq: true, order: :id

  # Convert github_data to a <tt>Hashie::Mash</tt> object so that delegation works
  def github_data
    @github_data ||= Hashie::Mash.new(read_attribute(:github_data))
  end

  def to_s
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery

  helper_method :current_user
  helper_method :signed_in?

  private

  def current_user
    return nil unless session[:user_id] || cookies.signed[:user_id]

    begin
      if session[:user_id]
        @current_user ||= User.find(session[:user_id])
      elsif cookies.signed[:user_id]
        @current_user ||= User.find(cookies.signed[:user_id])
      end
    rescue ActiveRecord::RecordNotFound
      nil
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def authenticate_user!
    unless signed_in?
      respond_to do |wants|
        wants.html { redirect_to sign_in_url, alert: 'You need to sign in for access to this page.' }
        wants.json { render json: {error: "You must be logged in on HubStar."} }
      end
    end
  end

  def allow_cross_site_origin
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_filter :allow_cross_site_origin
  before_filter :authenticate_user!, only: [:index]

  def index
    respond_to do |wants|
      wants.html { redirect_to root_path }
      # TODO: Not final
      wants.json { render json: current_user.repositories.collect { |r| r.name } }
    end
  end

  def show
    @repo  = Repository.find_or_initialize_by_name(params[:id])
    @users = @repo.users_with_priority_to(current_user)

    respond_to do |wants|
      wants.html
      wants.json { render json: @repo.to_json(user: current_user) }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/github'
  end

  def create
    data = request.env["omniauth.auth"][:extra][:raw_info]
    attributes = { :github_data => data, :github_access_token => request.env["omniauth.auth"][:credentials][:token] }
    user = User.find_or_create_by_username(data[:login], attributes)

    session[:user_id] = cookies.permanent.signed[:user_id] = user.id
    flash[:success] = 'Successfully signed in via GitHub!'
    redirect_to root_url
  end

  def destroy
    reset_session
    cookies.delete(:user_id)
    flash[:info] = 'You have been signed out.'
    redirect_to root_url
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  before_filter :allow_cross_site_origin
  before_filter :authenticate_user!, only: [:update, :destroy]

  # Star for the current user
  def update
    @repo = Repository.find_or_initialize_by_name(params[:id])

    if @repo.update_attributes(user: current_user)
      respond_to do |wants|
        wants.json { render json: @repo.to_json(user: current_user) }
      end
    else
      respond_to do |wants|
        wants.json { render json: {error: @repo.errors.full_messages} }
      end
    end
  end

  # Unstar for the current user
  def destroy
    @repo = Repository.find_by_name(params[:id])
    current_user.repositories.delete(@repo)

    respond_to do |wants|
      wants.json { render json: @repo.to_json(user: current_user) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_intro.html.erb
<div class="intro">
  <p><strong>HubStar</strong> is the missing "star" feature for
  <%= link_to('GitHub', 'https://github.com/') %> repositories. You can already
  star Gists, so why not repositories?</p>

  <h2>How does it work?</h2>

  <p>After signing in to HubStar with your GitHub account and installing a
  browser extension, you'll notice a new button next to the fork and watch
  buttons on any GitHub repository page:</p>

  <%= image_tag("http://f.cl.ly/items/1W08032V3h1113170C3Z/HubStar.jpg") %>

  <p>The new <strong>star button</strong> works just like the fork and watch
  buttons you're used to using on GitHub. Click the star to remember it for
  later, click it again to forget it.</p>

  <h2>Security & Privacy</h2>

  <p>On GitHub repository pages, the HubStar browser extension makes a
  <tt>GET</tt> request to HubStar's servers, passing along the URL of the
  currently viewed repository. It will only do this on <strong>public</strong>
  repositories. No information regarding private repositories is ever sent to
  external servers, or even read by the extension.</p>

  <p>Further, the source for the entire site, including the browser extensions,
  is <%= link_to('available on GitHub', 'https://github.com/tsigo/hubstar') %>.</p>

  <h2>Ready to get started?</h2>

  <p><%= link_to('Sign in', sign_in_path) %> with your GitHub account, then
  download a <%= link_to('browser extension', 'https://github.com/tsigo/hubstar/downloads') %>.</p>
</div>

app/views/dashboard/about.html.erb
<h1>About HubStar</h1>

<%= render partial: 'intro' %>

app/views/dashboard/index.html.erb
<%- if signed_in? %>

  <h2>My Starred Repositories</h2>

  <%= render partial: 'repositories/list', locals: {repositories: current_user.repositories} %>

<%- else %>

<div class="hero-unit">
  <div class="row">
    <div class="span1">
      <%= image_tag('star-64.png') %>
    </div>
    <div class="span8">
      <h1>HubStar</h1>
      <p>Is your GitHub activity feed overrun with projects you started
      watching just to remember them for later?</p>
      <p><strong>HubStar them instead!</strong></p>
    </div>
  </div>
</div>

<%= render partial: 'intro' %>

<%- end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HubStar</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "HubStar", root_path, class: 'brand' %>
        <ul class="nav">
          <li><%= link_to 'About', about_path %></li>
        </ul>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li class="dropdown">
              <%= link_to((current_user.to_s + content_tag(:b, nil, class: 'caret')).html_safe, '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'}) %>
              <ul class="dropdown-menu">
                <li><%= link_to('GitHub Profile', current_user.html_url) %></li>
                <li><%= link_to('Sign Out', sign_out_path, method: :delete, confirm: "Are you sure you want to log out?") %></li>
              </ul>
            </li>
            <li><%= image_tag current_user.avatar_url, size: '28x28' %></li>
          <% else %>
            <li><%= link_to 'Sign in with GitHub', sign_in_path, rel: 'nofollow' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="content">
      <div class="row">
        <div class="span12">
          <% flash.each do |type, message| %>
            <div class="alert alert-<%= type %> fade in">
              <a class="close" data-dismiss="alert">&times;</a>
              <%= message %>
            </div>
          <% end %>

          <%= yield %>
        </div>
      </div>
    </div>

    <footer>
      <div class="row">
        <div class="span6">
          <%= link_to "HubStar", root_url %> &copy; <%= Date.today.year %> Robert Speicher
          -- <%= link_to 'Fork me', 'https://github.com/tsigo/hubstar/' %> on GitHub!
        </div>
        <div class="span6 pull-right">
        </div>
      </div>
    </footer>
  </div>

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-29615500-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</body>
</html>

app/views/repositories/_list.html.erb
<% repositories.each do |repo| %>
  <div class="row repo-info">
    <div class="span9">
      <h3><%= link_to(repo.name, repo.link) %></h3>
      <p class="description"><%= repo.description %></p>
    </div>
    <div class="span3">
      <div class="row repo-stats">
        <div class="span1 hubstars hubstarred">
          <%= link_to(number_with_delimiter(repo.stars, delimiter: ','), repository_path(repo)) %>
        </div>
        <div class="span1 watchers">
          <span><%= number_with_delimiter(repo.watchers, delimiter: ',') %></span>
        </div>
        <div class="span1 forks">
          <span><%= number_with_delimiter(repo.forks, delimiter: ',') %></span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/repositories/show.html.erb
<h2>Users who starred <%= link_to(@repo.to_s, @repo.link) %></h2>

<% @users.each do |user| %>
  <div class="row user-info">
    <div class="span1 user-avatar"><%= image_tag(user.avatar_url, size: '48x48') %></div>
    <div class="span9">
      <h3><%= link_to(user.username, user.html_url) %></h3>
      <span class="description">
        <%= user.name %>
      </span>
    </div>
    <div class="span2 repo-stats">
      <%- if user == current_user %>
        <div class="hubstars hubstarred">
          <p class="hint">Toggle HubStar:</p>
          <%= link_to(@repo.stars, repository_path(@repo), class: 'toggle', data: {id: @repo.name}) %>
        </div>
      <%- end %>
    </div>
  </div>
<% end %>